package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.35

import (
	"com.ai.bff-purchase-order-inquiry/graph/model"
	"com.ai.bff-purchase-order-inquiry/grpc/client"
	"context"
)

// Order is the resolver for the order field.
func (r *queryResolver) Order(ctx context.Context) (*model.Order, error) {
	order, err := client.GetOrder(ctx, "1")
	if err != nil {
		return nil, err
	}
	return &model.Order{
		OrderID:     order.OrderId,
		Price:       order.Price,
		Quantity:    order.Quantity,
		CustomerID:  order.CustomerId,
		TotalAmount: order.TotalAmount,
		Status:      order.Status,
	}, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
