package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.35

import (
	"context"

	"com.ai.bff-purchase-order-inquiry/graph/model"
	"com.ai.bff-purchase-order-inquiry/grpc/client"
)

// Order is the resolver for the order field.
func (r *queryResolver) Order(ctx context.Context, id string) (*model.Order, error) {
	order, err := client.GetOrder(ctx, id)
	if err != nil {
		return nil, err
	}
	return &model.Order{
		OrderID:     int(order.OrderId),
		Price:       int(order.Price),
		Quantity:    int(order.Quantity),
		CustomerID:  int(order.CustomerId),
		TotalAmount: int(order.TotalAmount),
		Status:      order.Status,
	}, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
