// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Order struct {
	OrderID     int    `json:"orderId"`
	Price       int    `json:"price"`
	Quantity    int    `json:"quantity"`
	CustomerID  int    `json:"customerId"`
	TotalAmount int    `json:"totalAmount"`
	Status      string `json:"status"`
}
