// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Order struct {
	OrderID     int64  `json:"orderId"`
	Price       int64  `json:"price"`
	Quantity    int64  `json:"quantity"`
	CustomerID  int64  `json:"customerId"`
	TotalAmount int64  `json:"totalAmount"`
	Status      string `json:"status"`
}
